# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
description = ""
language = "javascript"
manifest_version = 2
name = "Hono"
service_id = "hkZAs7u4eE247BqEpEKfP1"

[scripts]
  build = "npm run build"
  post_init = "npm install"
